type="mysql"
[master]
host="192.168.10.23"
port=3306
username="root"
password="123456"
dbname="test"
charset="utf8"
max_open_conns=2000
max_idle_conns=200
conns_max_lifetime=300
[[slaves]]
host="192.168.10.23"
port=3306
username="root"
password="123456"
dbname="test"
charset="utf8"
max_open_conns=2000
max_idle_conns=200
conns_max_lifetime=300